[package]
name = "log-lock"
version = "0.1.3"
edition = "2021"

[features]
always-log = []

[dependencies]
derivative = "2.2.0"
parking_lot = "0.12.1"
tokio = { version = "1.29.1", features = ["macros", "sync"] }
